import pandas as pd
from pathlib import Path
RAW_DATA_PATH= Path("data/raw")
csv_files= list(RAW_DATA_PATH.glob("*.csv"))
print(f"Found {len(csv_files)} CSV files.")
for file_path in csv_files:
    df= pd.read_csv(file_path)
    print("=" * 60)
    print(f"FILE: {file_path.name}")
    print(f"Shape: {df.shape}")
    print("\nData Types:")
    print(df.dtypes)
    print("\nFirst 5 Rows:")
    print(df.head())
    print("\nMissing Values:")
    print(df.isnull().sum())
    print("\nDuplicate Rows:")
    print(df.duplicated().sum())
    if df.isnull().sum().sum() > 0:
        print("\nRows with missing values:")
        print(df[df.isnull().any(axis=1)])
    print("=" * 60)

fund_master= pd.read_csv("data/raw/1788499983024-b042c300-01_fund_master.csv")
print("\nFund Master:")
print(fund_master.head())
print("\nFund Houses:")
print(fund_master["fund_house"].unique())
print("\nCategories:")
print(fund_master["category"].unique())
print("\nSub Categories:")
print(fund_master["sub_category"].unique())
print("\nRisk Categories:")
print(fund_master["risk_category"].unique())
print("\nAMFI Codes:")
print(fund_master[["amfi_code", "fund_house", "scheme_name"]].head(10))
print("\nAMFI Code Count:")
print(fund_master["amfi_code"].nunique())

nav_history= pd.read_csv("data/raw/1788499983331-4389156d-02_nav_history.csv")
fund_codes= set(fund_master["amfi_code"])
nav_codes= set(nav_history["amfi_code"])
missing_codes= fund_codes - nav_codes
extra_codes= nav_codes - fund_codes
print("\nAMFI Code Validation:")
print("Codes in fund_master:", len(fund_codes))
print("Codes in nav_history:", len(nav_codes))
print("Missing from nav_history:", missing_codes)
print("Extra codes in nav_history:", extra_codes)